[project]
name = "bqm"
description = "bigquery meta data table utility"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = [
    "click",
    "sqlalchemy-bigquery>=1.12.0",
]

[project.scripts]
bqm= "main:main"
